=== lisp/de.setf.xml/tests/xml/aramaic.dtd
<!-- xml dtd for aramaic dictionary -->
<!-- the optional fields are hebrew forms, alternate forms,
cross-references, and notes -->
    <!ENTITY % OPTIONAL-FIELDS 'HB?, ALT?, TRF*, XRF?, NT*'>
    <!ENTITY % STATUS 'st CDATA #IMPLIED'>
         <!-- a dictionary is entry* -->
         <!-- an entry is root and subentry+ or citation form and words,
and note* -->
    <!ELEMENT  DICTIONARY (EN*) >
    <!ELEMENT  EN (((RT,SB+) | (CF,W*)),NT*) >
    <!ATTLIST EN hw ID #REQUIRED md NMTOKEN #REQUIRED>
         <!-- a subentry is an optional grammar, gloss, and citation form,
word*, and note* -->
    <!ELEMENT  SB (GR?,GL?,CF?,W*,NT*) >
    <!ATTLIST SB p (y|n) 'y'>
         <!-- a citation form is only obligatory word of a subentry -->
         <!-- a citation form has a gloss, grammatical info, and optional
fields -->
         <!-- cf and w form derived from id number -->
    <!ELEMENT  CF (GR,GL?,%OPTIONAL-FIELDS;) >
    <!ATTLIST CF id ID #REQUIRED >
         <!-- a word has grammatical info, maybe a gloss, and optional
fields -->
    <!ELEMENT W (GR,GL?,%OPTIONAL-FIELDS;) >
    <!ATTLIST W id ID #REQUIRED >
         <!-- root form content derived from entry hw number -->
         <!-- root has gloss and may have grammatical info -->
    <!ELEMENT RT (GR?,GL,%OPTIONAL-FIELDS;) >
    <!ELEMENT GL (#PCDATA) >
    <!ATTLIST GL %STATUS; >
    <!ELEMENT GR (#PCDATA) >
    <!ATTLIST GR %STATUS; >
    <!ELEMENT HB (#PCDATA) >
    <!ELEMENT ALT (#PCDATA) >
        <!-- text reference -->
    <!ELEMENT TRF (#PCDATA) >
    <!ELEMENT XRF (#PCDATA) >
    <!ELEMENT NT (#PCDATA) >

=== lisp/de.setf.xml/tests/xml/real-mini-aleph-het.xml
<?xml version='1.0' encoding='ISO-8859-1' standalone='no'?>
<!DOCTYPE DICTIONARY SYSTEM 'aramaic.dtd'>
<DICTIONARY>
<EN hw="h432" md="310898">
<CF id="w552"><GR>cn</GR><GL>flute</GL></CF></EN>
<EN hw="h153" md="310898"><RT><GR>vb</GR><GL>wish, want</GL><HB>ı·”</HB></RT>
<SB>
<W id="w2033"><GR>3sf pre</GR></W></SB></EN>
<EN hw="h627" md="310898"><RT><GR>vb</GR><GL>mourn</GL></RT>
<SB>
<CF id="w3498"><GR>3sm suf P I</GR></CF></SB>
<SB><W id="w3597"><GR st='?'>1s Q</GR><TRF>g37:35 strange syntax in
general, and is this an instance of abs pro suffix?</TRF></W>
</SB><NT>+ ÚÃÏ</NT></EN>
<EN hw="h1280" md="310898">
<CF id="w4337"><GR>cn sa</GR><GL>mourning</GL></CF>
<W id="w4336"><GR>sd</GR></W>
<W id="w2636"><GR>3sm</GR><NT>odd context</NT></W></EN>
</DICTIONARY>
