=== lisp/de.setf.xml/tests/xml/lisp.dtd
<!-- an xml dtd fur lisp definition forms
     19971127 changed LISP and BODY elements to explicitly recognise SEXP's
 -->
<!ELEMENT LISP ((DEFCLASS | DEFCONSTANT | DEFUN | DEFGENERIC |
                 DEFMACRO | DEFMETHOD | DEFPARAMETER | DEFSTRUCT |
                 DEFVAR | SEXP | ATOM)* ) >
<!ELEMENT DEFCLASS (NAME, CLASS-LIST, SLOT-LIST, (DOCUMENTATION | METACLASS)*) >
<!ELEMENT DEFCONSTANT (NAME, VALUE, DOCUMENTATION?) >
<!ELEMENT DEFUN (NAME, ARGUMENT-LIST, DOCUMENTATION?, BODY) >
<!ELEMENT DEFGENERIC (NAME, GENERIC-ARGUMENT-LIST, DOCUMENTATION?) >
<!ELEMENT DEFMACRO (NAME, ARGUMENT-LIST, DOCUMENTATION?, BODY) >
<!ELEMENT DEFMETHOD (NAME, QUALIFIER-LIST?, SPECIALIZED-ARGUMENT-LIST,
                           DOCUMENTATION?, BODY) >
<!ELEMENT DEFPARAMETER (NAME, VALUE, DOCUMENTATION?) >
<!ELEMENT DEFSTRUCT (NAME, INCLUDE?, STRUCTURE-SLOT-LIST) >
<!ELEMENT DEFVAR (NAME, (VALUE | (VALUE, DOCUMENTATION))?)>
<!ELEMENT LAMBDA (ARGUMENT-LIST, BODY) >

<!ELEMENT NAME (#PCDATA) >
<!ELEMENT KEYWORD (#PCDATA) >
<!ELEMENT INCLUDE (#PCDATA) >
<!ELEMENT QUALIFIER-LIST (QUALIFIER*) >
<!ELEMENT QUALIFIER (#PCDATA) >
<!ELEMENT ARGUMENT-LIST (ARGUMENT*,
                         (OPTIONAL, ARGUMENT)?,
                         (REST, ARGUMENT)?,
                         (KEY, KEYWORD-ARGUMENT*)?,
                         (AUX, DEFAULT-ARGUMENT*)?) >
<!ELEMENT GENERIC-ARGUMENT-LIST (ARGUMENT*,
                                (OPTIONAL, ARGUMENT)?,
                                (REST, ARGUMENT)?,
                                (KEY, ARGUMENT*)?,
                                (AUX, ARGUMENT*)?) >
<!ELEMENT SPECIALIZED-ARGUMENT-LIST (SPECIALIZED-ARGUMENT*,
                                    (OPTIONAL, ARGUMENT)?,
                                     (REST, ARGUMENT)?,
                                     (KEY, KEYWORD-ARGUMENT*)?,
                                     (AUX, DEFAULT-ARGUMENT*)?) >
<!ELEMENT REST (#PCDATA) >
<!ELEMENT AUX (#PCDATA) >
<!ELEMENT KEY (#PCDATA) >
<!ELEMENT OPTIONAL (NAME) >
<!ELEMENT ARGUMENT (NAME) >
<!ELEMENT KEYWORD-ARGUMENT (NAME | (NAME, DEFAULT) | (NAME, DEFAULT, KEYWORD)) >
<!ELEMENT DEFAULT-ARGUMENT (NAME | (NAME, DEFAULT)) >
<!ELEMENT DEFAULT (#PCDATA) >
<!ELEMENT SPECIALIZED-ARGUMENT ((NAME, SPECIALIZER) | NAME) >
<!ELEMENT SPECIALIZER (#PCDATA) >
<!ELEMENT CLASS-LIST (CLASS*) >
<!ELEMENT CLASS (#PCDATA) >
<!ELEMENT DOCUMENTATION (#PCDATA) >
<!ELEMENT SLOT-LIST (SLOT*) >
<!ELEMENT SLOT (NAME, DEFAULT, TYPE, DOCUMENTATION) >
<!ELEMENT STRUCTURE-SLOT-LIST (STRUCTURE-SLOT*) >
<!ELEMENT STRUCTURE-SLOT (NAME, DEFAULT, TYPE) >
<!ELEMENT VALUE (#PCDATA) >
<!ELEMENT TYPE (#PCDATA) >
<!ELEMENT METACLASS (#PCDATA) >
<!ELEMENT BODY (SEXP*) >
<!ELEMENT SEXP ((OPERATOR | LAMBDA), (SEXP | ATOM)*) >
<!ELEMENT OPERATOR (#PCDATA) >
<!ELEMENT ATOM (#PCDATA) >

=== lisp/de.setf.xml/tests/xml/lisp.xml
<?xml version="1.0" ?>
<!DOCTYPE LISP SYSTEM "lisp.dtd" [
 <!ATTLIST LISP xmlns CDATA '-//mecomnet.de//DTD Lisp (sort of)//en'>
 ] >

<LISP xmlns='lisp as xml'>
        <DEFUN>
         <NAME>asdf</NAME>
         <ARGUMENT-LIST>
          <ARGUMENT><NAME>arg-1</NAME></ARGUMENT>
          <ARGUMENT><NAME>arg-2</NAME></ARGUMENT>
          </ARGUMENT-LIST>
         <DOCUMENTATION>this is a test</DOCUMENTATION>
         <BODY>
          <SEXP><OPERATOR>this</OPERATOR>
               <ATOM>is</ATOM><ATOM>a</ATOM><ATOM>test</ATOM>
           </SEXP>
          <SEXP>
           <OPERATOR>to</OPERATOR>
           <ATOM>see</ATOM><ATOM>if</ATOM><ATOM>the</ATOM><ATOM>defun</ATOM><ATOM>model</ATOM><ATOM>works</ATOM>
           </SEXP>
          </BODY>
         </DEFUN>

        <DEFMETHOD>
         <NAME>asdf</NAME>
         <SPECIALIZED-ARGUMENT-LIST>
          <SPECIALIZED-ARGUMENT><NAME>arg-1</NAME><SPECIALIZER>a class</SPECIALIZER></SPECIALIZED-ARGUMENT>
          <SPECIALIZED-ARGUMENT><NAME>arg-2</NAME></SPECIALIZED-ARGUMENT>
          </SPECIALIZED-ARGUMENT-LIST>
         <DOCUMENTATION>this is a test for defmethod</DOCUMENTATION>
         <BODY><SEXP><OPERATOR>this</OPERATOR>
                <ATOM>is</ATOM><ATOM>a</ATOM><ATOM>test</ATOM>
                </SEXP>
               <SEXP><OPERATOR>to</OPERATOR>
                <ATOM>see</ATOM><ATOM>if</ATOM><ATOM>the</ATOM><ATOM>defun</ATOM><ATOM>model</ATOM><ATOM>works</ATOM>
                </SEXP>
               </BODY>
         </DEFMETHOD>

        <SEXP><OPERATOR>print</OPERATOR><ATOM>a-ok</ATOM></SEXP>

        <ATOM>EOF</ATOM>
  
        </LISP>
